services:
  notification_microservice_db:
    image: mysql
    restart: always
    ports:
      - "1000:3306"
    environment:
      - MYSQL_DATABASE=c2s_technical_challenge_users_notifications
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - c2s-technical-challenge-main-task-system_main-task-system-network

  notification_microservice_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 2000 -b '0.0.0.0'
    volumes:
      - ./:/rails
    ports:
      - "2000:2000"
    depends_on:
      - notification_microservice_db
    networks:
      - c2s-technical-challenge-main-task-system_main-task-system-network

networks:
  c2s-technical-challenge-main-task-system_main-task-system-network:
    external: true
